name: Build

on:
  pull_request: { }
  workflow_dispatch: { }
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

permissions:
  contents: read
  checks: write

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yml
